title: aegis1920
email: aegis1920@gmail.com
description: >- 
    안녕하세요? 방문해주셔서 감사합니다^^
baseurl: "" 
url: "" 
github_username: aegis1920

# Build settings
markdown: kramdown

kramdown:
    input: GFM
    syntax_highligter: rouge

plugins:
  - jekyll-feed


 
