title: aegis1920의 블로그
email: aegis1920@gmail.com
description: >- 
  개발 중인 블로그입니다.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  aegis1920

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Collections
collections:
  wiki:
    output: true
